apiVersion: v1
kind: Secret
metadata:
  namespace: resources-namespace
  name: k8s-secret
stringData:
  REDIS_PASSWORD: REDIS_PASSWORD
  MINIO_PASSWORD: MINIO_PASSWORD
  POSTGRES_PASSWORD: POSTGRES_PASSWORD
  REDIS_URL: redis://:REDIS_PASSWORD@redis-service:6379
  MINIO_URL: minio://minio:MINIO_PASSWORD@minio-service:9000
  POSTGRES_URL: postgres://postgres:POSTGRES_PASSWORD@postgres-service:5432/nestjs
type: Opaque