apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: resources-namespace
  name: k8s-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi