apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: khaclub/posts
      context: ./services/backend/1.posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.py'
            dest: .
    - image: khaclub/time
      context: ./services/backend/2.time
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.py'
            dest: .