apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs
          image: khaclub/nestjs
          imagePullPolicy: "Never"
          resources:
            requests:
              cpu: "500m"
              memory: "200Mi"
            limits:
              cpu: "700m"
              memory: "300Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-clusterip-srv
spec:
  selector:
    app: nestjs
  ports:
    - name: nestjs
      protocol: TCP
      port: 4000
      targetPort: 4000